"""icon_added

Revision ID: 019aa1dd27cd
Revises: 7c3c761bfedf
Create Date: 2026-03-01 17:17:17.948262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019aa1dd27cd'
down_revision = '7c3c761bfedf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('icon', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'icon')
    # ### end Alembic commands ###
