"""add_description_to_pdf_job

Revision ID: 0e814d6026ae
Revises: 6b2f86177148
Create Date: 2026-03-18 11:32:33.277078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e814d6026ae'
down_revision = '6b2f86177148'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_jobs', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('pdf_jobs', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pdf_jobs', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdf_jobs', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('pdf_jobs', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('pdf_jobs', 'description')
    # ### end Alembic commands ###
