"""add_subject_description_to_quiz

Revision ID: 0f2bf8a71ef5
Revises: 7dfe8d660104
Create Date: 2026-02-28 14:35:23.552143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2bf8a71ef5'
down_revision = '7dfe8d660104'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('quizzes', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'description')
    op.drop_column('quizzes', 'subject')
    # ### end Alembic commands ###
