"""colum_name_changed

Revision ID: 12eccc827fd8
Revises: 7c46b9a32d88
Create Date: 2026-03-18 17:13:25.083284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12eccc827fd8'
down_revision = '7c46b9a32d88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_jobs', sa.Column('number_questions', sa.Integer(), nullable=True))
    op.drop_column('pdf_jobs', 'question_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_jobs', sa.Column('question_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pdf_jobs', 'number_questions')
    # ### end Alembic commands ###
