"""enum_added

Revision ID: 17d43256e9eb
Revises: 7cfed3e2c54b
Create Date: 2026-03-13 15:07:15.103387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d43256e9eb'
down_revision = '7cfed3e2c54b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attempt_answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('session_participants', 'participant_status',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_participants', 'participant_status',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_constraint(None, 'attempt_answers', type_='foreignkey')
    # ### end Alembic commands ###
