"""Initial schema.

Everything the application needs before any later migration runs. The chain used
to start at 20260905_0001, which altered tables nobody had created yet, so a fresh
database could not be migrated at all — only databases built by hand before Alembic
was introduced.

The schema here is deliberately the state *before* 20260905_0001: naive timestamps,
no quiz_sessions.deadline_at, no telegram_* tables. The later migrations then apply
exactly as they did historically.

Revision ID: 20260901_0000
Revises:
Create Date: 2026-09-16
"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "20260901_0000"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=25), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_created_at'), 'subjects', ['created_at'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_index(op.f('ix_subjects_updated_at'), 'subjects', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.String(length=25), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_type'), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=False), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('education_level', sa.Enum('1-sinf', '2-sinf', '3-sinf', '4-sinf', '5-sinf', '6-sinf', '7-sinf', '8-sinf', '9-sinf', '10-sinf', '11-sinf', 'Universitet', name='education_level'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('student', 'schoolboy', 'teacher', name='usertype'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=False), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chats',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('chat_type', sa.Enum('PRIVATE', 'GROUP', 'CHANNEL', name='chat_type'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('last_message_text', sa.String(length=255), nullable=True),
    sa.Column('last_message_sender_id', sa.Integer(), nullable=True),
    sa.Column('last_message_created_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('direct_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_message_sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direct_key')
    )
    op.create_index(op.f('ix_chats_created_at'), 'chats', ['created_at'], unique=False)
    op.create_index(op.f('ix_chats_last_message_created_at'), 'chats', ['last_message_created_at'], unique=False)
    op.create_index(op.f('ix_chats_last_message_sender_id'), 'chats', ['last_message_sender_id'], unique=False)
    op.create_index(op.f('ix_chats_owner_id'), 'chats', ['owner_id'], unique=False)
    op.create_index(op.f('ix_chats_updated_at'), 'chats', ['updated_at'], unique=False)
    op.create_table('contacts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_user_friend')
    )
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_updated_at'), 'contacts', ['updated_at'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('FRIEND_REQUEST', 'FRIEND_ACCEPTED', 'TEST_INVITE', 'TEST_REMINDER', 'TEST_RESULT', 'ACHIEVEMENT', 'TEACHER_MESSAGE', 'COMPETITION_RESULT', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('action_type', sa.Enum('NONE', 'FRIEND_REQUEST', 'TEST_INVITE', 'OPEN_TEST', 'OPEN_CHAT', 'OPEN_RESULT', name='notificationactiontype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_updated_at'), 'notifications', ['updated_at'], unique=False)
    op.create_table('quizzes',
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('quiz_generate_type', sa.Enum('AI_GENERATE', 'PDF', 'MANUAL', 'UNDEFINED', name='quiz_generate_type'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_created_at'), 'quizzes', ['created_at'], unique=False)
    op.create_index(op.f('ix_quizzes_updated_at'), 'quizzes', ['updated_at'], unique=False)
    op.create_table('student_groups',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.Enum('PURPLE', 'BLUE', 'VIOLET', 'GREEN', 'YELLOW', 'RED', 'PINK', 'TEAL', 'ORANGE', 'CYAN', name='group_color'), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='group_status'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_teacher_group_name')
    )
    op.create_index(op.f('ix_student_groups_created_at'), 'student_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_groups_subject_id'), 'student_groups', ['subject_id'], unique=False)
    op.create_index(op.f('ix_student_groups_teacher_id'), 'student_groups', ['teacher_id'], unique=False)
    op.create_index('ix_student_groups_teacher_status', 'student_groups', ['teacher_id', 'status'], unique=False)
    op.create_index(op.f('ix_student_groups_updated_at'), 'student_groups', ['updated_at'], unique=False)
    op.create_table('user_subject',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subject_created_at'), 'user_subject', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_subject_updated_at'), 'user_subject', ['updated_at'], unique=False)
    op.create_table('chat_members',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='chat_member_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=False), nullable=False),
    sa.Column('last_read_message_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('chat_user_idx', 'chat_members', ['chat_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_chat_members_chat_id'), 'chat_members', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_members_created_at'), 'chat_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_members_updated_at'), 'chat_members', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chat_members_user_id'), 'chat_members', ['user_id'], unique=False)
    op.create_table('pdf_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.Integer(), nullable=True),
    sa.Column('number_questions', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='pdfjobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_jobs_created_at'), 'pdf_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pdf_jobs_updated_at'), 'pdf_jobs', ['updated_at'], unique=False)
    op.create_table('questions',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('table_markdown', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_updated_at'), 'questions', ['updated_at'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'running', 'finished', name='session_status'), server_default='waiting', nullable=False),
    sa.Column('session_type', sa.Enum('individual', 'group', 'public', name='session_type'), server_default='individual', nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_index(op.f('ix_quiz_sessions_created_at'), 'quiz_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_updated_at'), 'quiz_sessions', ['updated_at'], unique=False)
    op.create_table('student_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'student_id', name='uq_group_student')
    )
    op.create_index(op.f('ix_student_group_members_created_at'), 'student_group_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_group_members_group_id'), 'student_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_student_group_members_student_id'), 'student_group_members', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_group_members_updated_at'), 'student_group_members', ['updated_at'], unique=False)
    op.create_table('options',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=5), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_created_at'), 'options', ['created_at'], unique=False)
    op.create_index(op.f('ix_options_updated_at'), 'options', ['updated_at'], unique=False)
    op.create_table('question_images',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_images_created_at'), 'question_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_question_images_updated_at'), 'question_images', ['updated_at'], unique=False)
    op.create_table('quiz_session_groups',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'group_id', name='uq_session_group')
    )
    op.create_index(op.f('ix_quiz_session_groups_created_at'), 'quiz_session_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_session_groups_group_id'), 'quiz_session_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_quiz_session_groups_session_id'), 'quiz_session_groups', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_session_groups_updated_at'), 'quiz_session_groups', ['updated_at'], unique=False)
    op.create_table('session_participants',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('participant_status', sa.Enum('preparing', 'ready', 'disconnected', name='participant_status_enum'), server_default='preparing', nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=False), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_participants_created_at'), 'session_participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_participants_updated_at'), 'session_participants', ['updated_at'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('wrong_answers', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['session_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_created_at'), 'quiz_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_updated_at'), 'quiz_attempts', ['updated_at'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=5), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=False), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question')
    )
    op.create_index('idx_attempt_question', 'attempt_answers', ['attempt_id', 'question_id'], unique=False)
    op.create_index(op.f('ix_attempt_answers_created_at'), 'attempt_answers', ['created_at'], unique=False)
    op.create_index(op.f('ix_attempt_answers_updated_at'), 'attempt_answers', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_answers_updated_at'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_created_at'), table_name='attempt_answers')
    op.drop_index('idx_attempt_question', table_name='attempt_answers')
    op.drop_table('attempt_answers')
    op.drop_index(op.f('ix_quiz_attempts_updated_at'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_created_at'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_session_participants_updated_at'), table_name='session_participants')
    op.drop_index(op.f('ix_session_participants_created_at'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_quiz_session_groups_updated_at'), table_name='quiz_session_groups')
    op.drop_index(op.f('ix_quiz_session_groups_session_id'), table_name='quiz_session_groups')
    op.drop_index(op.f('ix_quiz_session_groups_group_id'), table_name='quiz_session_groups')
    op.drop_index(op.f('ix_quiz_session_groups_created_at'), table_name='quiz_session_groups')
    op.drop_table('quiz_session_groups')
    op.drop_index(op.f('ix_question_images_updated_at'), table_name='question_images')
    op.drop_index(op.f('ix_question_images_created_at'), table_name='question_images')
    op.drop_table('question_images')
    op.drop_index(op.f('ix_options_updated_at'), table_name='options')
    op.drop_index(op.f('ix_options_created_at'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_student_group_members_updated_at'), table_name='student_group_members')
    op.drop_index(op.f('ix_student_group_members_student_id'), table_name='student_group_members')
    op.drop_index(op.f('ix_student_group_members_group_id'), table_name='student_group_members')
    op.drop_index(op.f('ix_student_group_members_created_at'), table_name='student_group_members')
    op.drop_table('student_group_members')
    op.drop_index(op.f('ix_quiz_sessions_updated_at'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_created_at'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_questions_updated_at'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_pdf_jobs_updated_at'), table_name='pdf_jobs')
    op.drop_index(op.f('ix_pdf_jobs_created_at'), table_name='pdf_jobs')
    op.drop_table('pdf_jobs')
    op.drop_index(op.f('ix_chat_members_user_id'), table_name='chat_members')
    op.drop_index(op.f('ix_chat_members_updated_at'), table_name='chat_members')
    op.drop_index(op.f('ix_chat_members_created_at'), table_name='chat_members')
    op.drop_index(op.f('ix_chat_members_chat_id'), table_name='chat_members')
    op.drop_index('chat_user_idx', table_name='chat_members')
    op.drop_table('chat_members')
    op.drop_index(op.f('ix_user_subject_updated_at'), table_name='user_subject')
    op.drop_index(op.f('ix_user_subject_created_at'), table_name='user_subject')
    op.drop_table('user_subject')
    op.drop_index(op.f('ix_student_groups_updated_at'), table_name='student_groups')
    op.drop_index('ix_student_groups_teacher_status', table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_teacher_id'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_subject_id'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_created_at'), table_name='student_groups')
    op.drop_table('student_groups')
    op.drop_index(op.f('ix_quizzes_updated_at'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_created_at'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_contacts_updated_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_chats_updated_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_owner_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_message_sender_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_message_created_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_at'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_updated_at'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_created_at'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
