"""group_model_addeds

Revision ID: 221e9fd27d2b
Revises: 4b6b0f7e0527
Create Date: 2026-03-23 07:47:14.300389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221e9fd27d2b'
down_revision = '4b6b0f7e0527'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_groups',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.Enum('PURPLE', 'BLUE', 'VIOLET', 'GREEN', 'YELLOW', 'RED', 'PINK', 'TEAL', 'ORANGE', 'CYAN', name='group_color'), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='group_status'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_teacher_group_name')
    )
    op.create_index(op.f('ix_student_groups_created_at'), 'student_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_groups_subject_id'), 'student_groups', ['subject_id'], unique=False)
    op.create_index(op.f('ix_student_groups_teacher_id'), 'student_groups', ['teacher_id'], unique=False)
    op.create_index('ix_student_groups_teacher_status', 'student_groups', ['teacher_id', 'status'], unique=False)
    op.create_index(op.f('ix_student_groups_updated_at'), 'student_groups', ['updated_at'], unique=False)
    op.create_table('student_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'student_id', name='uq_group_student')
    )
    op.create_index(op.f('ix_student_group_members_created_at'), 'student_group_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_group_members_group_id'), 'student_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_student_group_members_student_id'), 'student_group_members', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_group_members_updated_at'), 'student_group_members', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_group_members_updated_at'), table_name='student_group_members')
    op.drop_index(op.f('ix_student_group_members_student_id'), table_name='student_group_members')
    op.drop_index(op.f('ix_student_group_members_group_id'), table_name='student_group_members')
    op.drop_index(op.f('ix_student_group_members_created_at'), table_name='student_group_members')
    op.drop_table('student_group_members')
    op.drop_index(op.f('ix_student_groups_updated_at'), table_name='student_groups')
    op.drop_index('ix_student_groups_teacher_status', table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_teacher_id'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_subject_id'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_created_at'), table_name='student_groups')
    op.drop_table('student_groups')
    # ### end Alembic commands ###
