"""add unique constraint attempt_question

Revision ID: 2a48839dcc91
Revises: 87fe2ad6f7f9
Create Date: 2026-02-25 10:24:51.996301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a48839dcc91'
down_revision = '87fe2ad6f7f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_attempt_question', 'attempt_answers', ['attempt_id', 'question_id'], unique=False)
    op.create_unique_constraint('uq_attempt_question', 'attempt_answers', ['attempt_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attempt_question', 'attempt_answers', type_='unique')
    op.drop_index('idx_attempt_question', table_name='attempt_answers')
    # ### end Alembic commands ###
