"""new_cahgne

Revision ID: 3d1b5f2e9267
Revises: 12eccc827fd8
Create Date: 2026-03-18 17:30:37.147517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1b5f2e9267'
down_revision = '12eccc827fd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_jobs', sa.Column('question_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_jobs', 'question_count')
    # ### end Alembic commands ###
