"""group_model_added

Revision ID: 4b6b0f7e0527
Revises: 3d1b5f2e9267
Create Date: 2026-03-23 07:00:17.240252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6b0f7e0527'
down_revision = '3d1b5f2e9267'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
