"""Pdf_job_model_addeds

Revision ID: 727e5184d656
Revises: 957e3dde18a2
Create Date: 2026-03-02 12:33:41.496362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727e5184d656'
down_revision = '957e3dde18a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
