"""type_added

Revision ID: 7c3c761bfedf
Revises: 33a95673393f
Create Date: 2026-03-01 17:14:34.480311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3c761bfedf'
down_revision = '33a95673393f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'type')
    # ### end Alembic commands ###
