"""add_new_changes

Revision ID: 7c46b9a32d88
Revises: b223f2a086d9
Create Date: 2026-03-18 17:06:55.646212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c46b9a32d88'
down_revision = 'b223f2a086d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
