"""participant_status_added

Revision ID: 7cfed3e2c54b
Revises: e380ec034290
Create Date: 2026-03-12 05:08:22.744409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfed3e2c54b'
down_revision = 'e380ec034290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_participants', sa.Column('participant_status', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_participants', 'participant_status')
    # ### end Alembic commands ###
