"""role_and_subject_added

Revision ID: 7dfe8d660104
Revises: 2a48839dcc91
Create Date: 2026-02-27 05:52:01.814856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfe8d660104'
down_revision = '2a48839dcc91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE usertype AS ENUM ('schoolboy', 'teacher', 'admin');")
    op.create_table('subjects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_created_at'), 'subjects', ['created_at'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_index(op.f('ix_subjects_updated_at'), 'subjects', ['updated_at'], unique=False)
    op.create_table('user_subject',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subject_created_at'), 'user_subject', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_subject_updated_at'), 'user_subject', ['updated_at'], unique=False)
    op.add_column('users', sa.Column('role', sa.Enum('student', 'schoolboy', 'teacher', name='usertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute('DROP TYPE usertype;')
    op.drop_index(op.f('ix_user_subject_updated_at'), table_name='user_subject')
    op.drop_index(op.f('ix_user_subject_created_at'), table_name='user_subject')
    op.drop_table('user_subject')
    op.drop_index(op.f('ix_subjects_updated_at'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_created_at'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
