"""add_new_colum_for_user_model

Revision ID: 7eeb42785e11
Revises: 17d43256e9eb
Create Date: 2026-03-13 20:10:57.648791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eeb42785e11'
down_revision = '17d43256e9eb'
branch_labels = None
depends_on = None
from sqlalchemy.dialects import postgresql
education_level_enum = postgresql.ENUM(
    "1-sinf",
    "2-sinf",
    "3-sinf",
    "4-sinf",
    "5-sinf",
    "6-sinf",
    "7-sinf",
    "8-sinf",
    "9-sinf",
    "10-sinf",
    "11-sinf",
    "Universitet",
    name="education_level"
)

def upgrade() -> None:
    education_level_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.String(length=25), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('school_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('education_level', sa.Enum('CLASS_1', 'CLASS_2', 'CLASS_3', 'CLASS_4', 'CLASS_5', 'CLASS_6', 'CLASS_7', 'CLASS_8', 'CLASS_9', 'CLASS_10', 'CLASS_11', 'UNIVERSITY', name='education_level'), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'education_level')
    op.drop_column('users', 'school_name')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
