"""subject_and_description

Revision ID: 847ff361396e
Revises: 0e814d6026ae
Create Date: 2026-03-18 16:14:55.747568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847ff361396e'
down_revision = '0e814d6026ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_jobs', sa.Column('subject', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pdf_jobs', 'subjects', ['subject'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdf_jobs', type_='foreignkey')
    op.drop_column('pdf_jobs', 'subject')
    # ### end Alembic commands ###
