"""date_time_changed

Revision ID: 87fe2ad6f7f9
Revises: b2eaa0b25349
Create Date: 2026-02-24 05:40:43.129478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fe2ad6f7f9'
down_revision = 'b2eaa0b25349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
