"""durition_minute_not_none

Revision ID: 910f58e3a18c
Revises: e95ab977a854
Create Date: 2026-02-24 05:28:21.080380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910f58e3a18c'
down_revision = 'e95ab977a854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_sessions', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_sessions', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
