"""add_session_statussd

Revision ID: 95679ba51014
Revises: 693d56965cf7
Create Date: 2026-03-25 15:58:18.273266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '95679ba51014'
down_revision = '693d56965cf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    session_status_enum = postgresql.ENUM(
        'waiting', 'running', 'finished',
        name='session_status'
    )
    session_type_enum = postgresql.ENUM(
        'individual', 'group', 'public',
        name='session_type'
    )

    session_status_enum.create(op.get_bind(), checkfirst=True)
    session_type_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'quiz_sessions',
        'status',
        existing_type=sa.VARCHAR(),
        type_=session_status_enum,
        postgresql_using='status::session_status',
        existing_nullable=False,
    )

    op.alter_column(
        'quiz_sessions',
        'session_type',
        existing_type=sa.VARCHAR(),
        type_=session_type_enum,
        postgresql_using='session_type::session_type',
        existing_nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
