"""Pdf_job_model_added

Revision ID: 957e3dde18a2
Revises: 019aa1dd27cd
Create Date: 2026-03-02 11:04:23.121502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957e3dde18a2'
down_revision = '019aa1dd27cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
