"""unique_uq_user_friend

Revision ID: 9fe3d76d5ba7
Revises: b4ca8762dee1
Create Date: 2026-03-05 09:43:26.785933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe3d76d5ba7'
down_revision = 'b4ca8762dee1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_friend', 'contacts', ['user_id', 'friend_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_friend', 'contacts', type_='unique')
    # ### end Alembic commands ###
