"""new_change

Revision ID: b223f2a086d9
Revises: b91b8892ba7d
Create Date: 2026-03-18 16:56:54.184488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b223f2a086d9'
down_revision = 'b91b8892ba7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
