"""end_time_changed_to_finished_at

Revision ID: b2eaa0b25349
Revises: 910f58e3a18c
Create Date: 2026-02-24 05:29:55.812260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2eaa0b25349'
down_revision = '910f58e3a18c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('finished_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('quiz_sessions', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('quiz_sessions', 'finished_at')
    # ### end Alembic commands ###
