"""subject_and_description

Revision ID: b60edcacf91e
Revises: 847ff361396e
Create Date: 2026-03-18 16:18:35.140439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60edcacf91e'
down_revision = '847ff361396e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
