"""max_participant_add

Revision ID: b8b2ae514d61
Revises: 3637bc6c42d6
Create Date: 2026-03-04 10:38:24.717563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b2ae514d61'
down_revision = '3637bc6c42d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('max_participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'max_participants')
    # ### end Alembic commands ###
