"""column_changed

Revision ID: b91b8892ba7d
Revises: b60edcacf91e
Create Date: 2026-03-18 16:27:35.442653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91b8892ba7d'
down_revision = 'b60edcacf91e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
