"""change color

Revision ID: bc2054bc05e8
Revises: cb06a8eac6a8
Create Date: 2026-03-24 18:09:14.975704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc2054bc05e8'
down_revision = 'cb06a8eac6a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_groups', 'color',
               existing_type=postgresql.ENUM('PURPLE', 'BLUE', 'VIOLET', 'GREEN', 'YELLOW', 'RED', 'PINK', 'TEAL', 'ORANGE', 'CYAN', name='group_color'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_groups', 'color',
               existing_type=postgresql.ENUM('PURPLE', 'BLUE', 'VIOLET', 'GREEN', 'YELLOW', 'RED', 'PINK', 'TEAL', 'ORANGE', 'CYAN', name='group_color'),
               nullable=False)
    # ### end Alembic commands ###
