"""session_group_added

Revision ID: cb06a8eac6a8
Revises: 221e9fd27d2b
Create Date: 2026-03-23 08:59:54.944581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb06a8eac6a8'
down_revision = '221e9fd27d2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_session_groups',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'group_id', name='uq_session_group')
    )
    op.create_index(op.f('ix_quiz_session_groups_created_at'), 'quiz_session_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_session_groups_group_id'), 'quiz_session_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_quiz_session_groups_session_id'), 'quiz_session_groups', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_session_groups_updated_at'), 'quiz_session_groups', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_session_groups_updated_at'), table_name='quiz_session_groups')
    op.drop_index(op.f('ix_quiz_session_groups_session_id'), table_name='quiz_session_groups')
    op.drop_index(op.f('ix_quiz_session_groups_group_id'), table_name='quiz_session_groups')
    op.drop_index(op.f('ix_quiz_session_groups_created_at'), table_name='quiz_session_groups')
    op.drop_table('quiz_session_groups')
    # ### end Alembic commands ###
