"""end_time_added_to_quiz_session

Revision ID: e95ab977a854
Revises: 74eaeb25d81f
Create Date: 2026-02-24 05:26:26.928877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95ab977a854'
down_revision = '74eaeb25d81f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('end_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'end_time')
    # ### end Alembic commands ###
