"""Seed content: the school subjects and the ready quizzes written for each one.

Only data lives here — :mod:`seed_subjects` owns the database work. Every subject
carries three quizzes that climb in difficulty, so a fresh deploy already has a
catalogue a student can work through:

* ``asosiy bilimlar testi``   — 5 oson / 3 o'rta / 2 qiyin
* ``mustahkamlash testi``     — 2 oson / 6 o'rta / 2 qiyin
* ``murakkab savollar testi`` — 4 o'rta / 6 qiyin

Adding a subject or a quiz means editing this file only. Quiz titles are the
identity used for idempotency, so never reword an existing one: a renamed quiz
is written again as a new row next to the old one.
"""

from __future__ import annotations

EASY = "oson"
MEDIUM = "o'rta"
HARD = "qiyin"

#: Option labels, in order. The correct answer is given as an index into this.
LABELS = ("A", "B", "C", "D")

#: Every quiz holds exactly this many questions.
QUESTIONS_PER_QUIZ = 10


def question(text: str, difficulty: str, topic: str, options: list[str], answer: int) -> dict:
    """Build one question; ``answer`` is the 0-based index of the correct option."""
    return {
        "text": text,
        "difficulty": difficulty,
        "topic": topic,
        "options": options,
        "answer": answer,
    }


def quiz(title: str, description: str, questions: list[dict]) -> dict:
    return {"title": title, "description": description, "questions": questions}


SUBJECTS: list[dict] = [
    {
        "name": "Matematika",
        "type": "math",
        "icon": "calculator",
        "quizzes": [
            quiz(
                "Matematika: asosiy bilimlar testi",
                "Arifmetika, algebra va geometriya asoslari bo'yicha "
                "10 ta savoldan iborat boshlang'ich daraja testi.",
                [
                    question("7 × 8 amalining natijasi nechaga teng?", EASY, "Arifmetika",
                             ["48", "54", "56", "63"], 2),
                    question("144 sonining kvadrat ildizi nechaga teng?", EASY, "Arifmetika",
                             ["12", "14", "16", "24"], 0),
                    question("200 sonining 25 foizi nechaga teng?", EASY, "Foiz",
                             ["25", "40", "50", "75"], 2),
                    question("Uchburchakning ichki burchaklari yig'indisi necha gradus?", EASY, "Geometriya",
                             ["90°", "180°", "270°", "360°"], 1),
                    question("x + 5 = 12 tenglamada x nechaga teng?", EASY, "Tenglamalar",
                             ["5", "6", "7", "17"], 2),
                    question("Radiusi 5 sm bo'lgan doiraning yuzi nechaga teng? (π ≈ 3,14)", MEDIUM, "Geometriya",
                             ["31,4 sm²", "78,5 sm²", "157 sm²", "25 sm²"], 1),
                    question("2x − 3 = 11 tenglamaning ildizi nechaga teng?", MEDIUM, "Tenglamalar",
                             ["4", "5", "7", "8"], 2),
                    question("Arifmetik progressiyada a₁ = 3, d = 4 bo'lsa, a₁₀ nechaga teng?", MEDIUM, "Progressiya",
                             ["36", "39", "40", "43"], 1),
                    question("x² − 5x + 6 = 0 tenglama ildizlarining yig'indisi nechaga teng?", HARD, "Kvadrat tenglama",
                             ["−5", "1", "5", "6"], 2),
                    question("log₂32 + log₂2 ifodaning qiymati nechaga teng?", HARD, "Logarifm",
                             ["5", "6", "7", "16"], 1),
                ],
            ),
            quiz(
                "Matematika: mustahkamlash testi",
                "Algebra, geometriya va progressiyalar bo'yicha o'rta darajadagi "
                "10 ta savol.",
                [
                    question("300 sonining 15 foizi nechaga teng?", EASY, "Foiz",
                             ["30", "45", "50", "60"], 1),
                    question("Tomonlari 5 sm va 3 sm bo'lgan to'g'ri to'rtburchakning perimetri nechaga teng?",
                             EASY, "Geometriya",
                             ["8 sm", "15 sm", "16 sm", "30 sm"], 2),
                    question("3x + 7 = 25 tenglamaning ildizi nechaga teng?", MEDIUM, "Tenglamalar",
                             ["5", "6", "7", "9"], 1),
                    question("(a + b)² ifodasi qanday yoyiladi?", MEDIUM, "Qisqa ko'paytirish formulalari",
                             ["a² + b²", "a² + 2ab + b²", "a² − 2ab + b²", "a² + ab + b²"], 1),
                    question("Geometrik progressiyada b₁ = 2, q = 3 bo'lsa, b₄ nechaga teng?", MEDIUM, "Progressiya",
                             ["18", "54", "81", "162"], 1),
                    question("Katetlari 6 sm va 8 sm bo'lgan to'g'ri burchakli uchburchakning gipotenuzasi nechaga teng?",
                             MEDIUM, "Pifagor teoremasi",
                             ["10 sm", "12 sm", "14 sm", "48 sm"], 0),
                    question("2⁵ × 2³ ifodaning qiymati nechaga teng?", MEDIUM, "Darajalar",
                             ["64", "128", "256", "512"], 2),
                    question("4, 8, 10 va 14 sonlarining o'rta arifmetigi nechaga teng?", MEDIUM, "Statistika",
                             ["8", "9", "10", "12"], 1),
                    question("x² − 7x + 12 = 0 tenglama ildizlarining ko'paytmasi nechaga teng?",
                             HARD, "Kvadrat tenglama",
                             ["−12", "−7", "7", "12"], 3),
                    question("Arifmetik progressiyada a₁ = 2, d = 3 bo'lsa, dastlabki 10 ta had yig'indisi nechaga teng?",
                             HARD, "Progressiya",
                             ["145", "155", "165", "175"], 1),
                ],
            ),
            quiz(
                "Matematika: murakkab savollar testi",
                "Logarifm, hosila, trigonometriya va kombinatorika bo'yicha "
                "yuqori darajadagi 10 ta savol.",
                [
                    question("5! (besh faktorial) nechaga teng?", MEDIUM, "Kombinatorika",
                             ["24", "60", "120", "720"], 2),
                    question("1/2 + 1/3 yig'indisi nechaga teng?", MEDIUM, "Kasrlar",
                             ["2/5", "5/6", "1/6", "3/5"], 1),
                    question("Radiusi 7 sm bo'lgan aylananing uzunligi nechaga teng? (π ≈ 3,14)",
                             MEDIUM, "Geometriya",
                             ["21,98 sm", "43,96 sm", "153,86 sm", "14 sm"], 1),
                    question("|x − 3| = 5 tenglamaning ildizlari qaysilar?", MEDIUM, "Modul",
                             ["x = 8 va x = 2", "x = 8 va x = −2", "x = −8 va x = 2", "x = 5 va x = 3"], 1),
                    question("log₂8 + log₂4 ifodaning qiymati nechaga teng?", HARD, "Logarifm",
                             ["5", "6", "12", "32"], 0),
                    question("y = x³ funksiyaning hosilasi qaysi?", HARD, "Hosila",
                             ["3x", "3x²", "x²/3", "x⁴/4"], 1),
                    question("x + y = 10 va x − y = 4 sistemasida x nechaga teng?", HARD, "Tenglamalar sistemasi",
                             ["3", "5", "7", "8"], 2),
                    question("sin30° + cos60° yig'indisi nechaga teng?", HARD, "Trigonometriya",
                             ["0,5", "1", "1,5", "√3/2"], 1),
                    question("Geometrik progressiyada b₁ = 3, q = 2 bo'lsa, dastlabki 5 ta had yig'indisi nechaga teng?",
                             HARD, "Progressiya",
                             ["62", "93", "96", "189"], 1),
                    question("5 ta elementdan 2 tasini tanlash necha xil usulda amalga oshiriladi?",
                             HARD, "Kombinatorika",
                             ["10", "20", "25", "120"], 0),
                ],
            ),
        ],
    },
    {
        "name": "Fizika",
        "type": "physics",
        "icon": "zap",
        "quizzes": [
            quiz(
                "Fizika: asosiy bilimlar testi",
                "Mexanika, energiya va elektr asoslari bo'yicha "
                "10 ta savoldan iborat boshlang'ich daraja testi.",
                [
                    question("Tezlikning SI tizimidagi o'lchov birligi qaysi?", EASY, "O'lchov birliklari",
                             ["m/s", "km/soat", "N", "J"], 0),
                    question("Yorug'likning vakuumdagi tezligi taxminan nechaga teng?", EASY, "Optika",
                             ["3 000 km/s", "30 000 km/s", "300 000 km/s", "3 000 000 km/s"], 2),
                    question("Kuchning SI tizimidagi o'lchov birligi qaysi?", EASY, "O'lchov birliklari",
                             ["Joul", "Vatt", "Nyuton", "Paskal"], 2),
                    question("Yer yuzasida erkin tushish tezlanishi taxminan nechaga teng?", EASY, "Mexanika",
                             ["5,6 m/s²", "9,8 m/s²", "10,8 m/s²", "12 m/s²"], 1),
                    question("Normal atmosfera bosimida suv necha gradusda qaynaydi?", EASY, "Issiqlik",
                             ["0 °C", "50 °C", "100 °C", "212 °C"], 2),
                    question("Massasi 2 kg bo'lgan jismga 6 N kuch ta'sir etsa, tezlanish nechaga teng?", MEDIUM, "Dinamika",
                             ["2 m/s²", "3 m/s²", "8 m/s²", "12 m/s²"], 1),
                    question("10 soniyada 500 J ish bajarilgan bo'lsa, quvvat nechaga teng?", MEDIUM, "Ish va quvvat",
                             ["5 Vt", "50 Vt", "500 Vt", "5000 Vt"], 1),
                    question("Massasi 4 kg, tezligi 3 m/s bo'lgan jismning kinetik energiyasi nechaga teng?", MEDIUM, "Energiya",
                             ["6 J", "12 J", "18 J", "36 J"], 2),
                    question("2 Ω va 3 Ω qarshiliklar parallel ulansa, umumiy qarshilik nechaga teng?", HARD, "Elektr toki",
                             ["0,6 Ω", "1,2 Ω", "2,5 Ω", "5 Ω"], 1),
                    question("Matematik mayatnik uzunligi 4 marta oshirilsa, uning tebranish davri qanday o'zgaradi?",
                             HARD, "Tebranishlar",
                             ["2 marta kamayadi", "O'zgarmaydi", "2 marta ortadi", "4 marta ortadi"], 2),
                ],
            ),
            quiz(
                "Fizika: mustahkamlash testi",
                "Om qonuni, harakat, zichlik va energiya hisoblari bo'yicha "
                "o'rta darajadagi 10 ta savol.",
                [
                    question("Quvvatning SI tizimidagi o'lchov birligi qaysi?", EASY, "O'lchov birliklari",
                             ["Joul", "Vatt", "Nyuton", "Amper"], 1),
                    question("Elektr tok kuchining o'lchov birligi qaysi?", EASY, "Elektr toki",
                             ["Volt", "Om", "Amper", "Vatt"], 2),
                    question("Kuchlanish 12 V, qarshilik 4 Ω bo'lsa, tok kuchi nechaga teng?", MEDIUM, "Om qonuni",
                             ["3 A", "4 A", "8 A", "48 A"], 0),
                    question("Tezligi 5 m/s bo'lgan jism 20 soniyada qancha yo'l bosadi?", MEDIUM, "Tekis harakat",
                             ["4 m", "25 m", "100 m", "400 m"], 2),
                    question("Massasi 3 kg jism 10 m balandlikda qanday potensial energiyaga ega? (g ≈ 10 m/s²)",
                             MEDIUM, "Energiya",
                             ["30 J", "150 J", "300 J", "3000 J"], 2),
                    question("Massasi 200 g, hajmi 100 sm³ bo'lgan jismning zichligi nechaga teng?", MEDIUM, "Zichlik",
                             ["0,5 g/sm³", "2 g/sm³", "20 g/sm³", "200 g/sm³"], 1),
                    question("Tovushning havodagi tezligi taxminan nechaga teng?", MEDIUM, "Tovush",
                             ["34 m/s", "340 m/s", "3400 m/s", "300 000 m/s"], 1),
                    question("Yorug'likning qaytish qonuniga ko'ra tushish burchagi qanday bo'ladi?", MEDIUM, "Optika",
                             ["Qaytish burchagidan katta", "Qaytish burchagiga teng",
                              "Qaytish burchagidan kichik", "Har doim 90°"], 1),
                    question("2 Ω va 3 Ω qarshiliklar ketma-ket ulansa, umumiy qarshilik nechaga teng?",
                             HARD, "Elektr toki",
                             ["1,2 Ω", "2,5 Ω", "5 Ω", "6 Ω"], 2),
                    question("Jism erkin tushayotganda 3 soniyada qancha yo'l bosadi? (g ≈ 10 m/s²)",
                             HARD, "Erkin tushish",
                             ["15 m", "30 m", "45 m", "90 m"], 2),
                ],
            ),
            quiz(
                "Fizika: murakkab savollar testi",
                "Impuls, saqlanish qonunlari, elektr zanjirlari va tebranishlar "
                "bo'yicha yuqori darajadagi 10 ta savol.",
                [
                    question("Massasi 2 kg, tezligi 5 m/s bo'lgan jismning impulsi nechaga teng?", MEDIUM, "Impuls",
                             ["2,5 kg·m/s", "10 kg·m/s", "25 kg·m/s", "50 kg·m/s"], 1),
                    question("Arximed kuchi nimaga bog'liq emas?", MEDIUM, "Gidrostatika",
                             ["Suyuqlik zichligiga", "Jism hajmiga",
                              "Jism moddasining turiga", "Erkin tushish tezlanishiga"], 2),
                    question("Tekis to'g'ri chiziqli harakatda tezlanish nechaga teng?", MEDIUM, "Kinematika",
                             ["0", "1 m/s²", "9,8 m/s²", "Tezlikka teng"], 0),
                    question("Issiqlik miqdorini hisoblash formulasi qaysi?", MEDIUM, "Issiqlik",
                             ["Q = cmΔt", "Q = mgh", "Q = mv²/2", "Q = UIt/2"], 0),
                    question("4 Ω va 4 Ω qarshiliklar parallel ulansa, umumiy qarshilik nechaga teng?",
                             HARD, "Elektr zanjirlari",
                             ["1 Ω", "2 Ω", "4 Ω", "8 Ω"], 1),
                    question("Jismning tezligi 2 marta oshsa, kinetik energiyasi qanday o'zgaradi?",
                             HARD, "Energiya",
                             ["2 marta ortadi", "3 marta ortadi", "4 marta ortadi", "O'zgarmaydi"], 2),
                    question("Izotermik jarayonda gaz bosimi 2 marta oshsa, hajmi qanday o'zgaradi?",
                             HARD, "Molekulyar fizika",
                             ["2 marta ortadi", "2 marta kamayadi", "4 marta kamayadi", "O'zgarmaydi"], 1),
                    question("Matematik mayatnikning tebranish davri nimaga bog'liq emas?", HARD, "Tebranishlar",
                             ["Mayatnik uzunligiga", "Erkin tushish tezlanishiga",
                              "Yukning massasiga", "Tebranish joyiga"], 2),
                    question("Kuchlanish 220 V, tok kuchi 0,5 A bo'lsa, elektr quvvati nechaga teng?",
                             HARD, "Elektr quvvati",
                             ["44 Vt", "110 Vt", "440 Vt", "1100 Vt"], 1),
                    question("Suvning yorug'lik sindirish ko'rsatkichi taxminan nechaga teng?", HARD, "Optika",
                             ["1,00", "1,33", "1,50", "2,42"], 1),
                ],
            ),
        ],
    },
    {
        "name": "Kimyo",
        "type": "chemistry",
        "icon": "flask",
        "quizzes": [
            quiz(
                "Kimyo: asosiy bilimlar testi",
                "Elementlar, formulalar va reaksiyalar bo'yicha "
                "10 ta savoldan iborat boshlang'ich daraja testi.",
                [
                    question("Suvning kimyoviy formulasi qaysi?", EASY, "Formulalar",
                             ["H₂O", "CO₂", "O₂", "NaCl"], 0),
                    question("Kislorod elementining kimyoviy belgisi qaysi?", EASY, "Elementlar",
                             ["O", "Os", "K", "Ox"], 0),
                    question("Osh tuzining kimyoviy formulasi qaysi?", EASY, "Formulalar",
                             ["KCl", "NaCl", "NaOH", "HCl"], 1),
                    question("Vodorod elementining davriy jadvaldagi tartib raqami nechaga teng?", EASY, "Davriy jadval",
                             ["1", "2", "8", "12"], 0),
                    question("Davriy jadvaldagi eng yengil element qaysi?", EASY, "Davriy jadval",
                             ["Geliy", "Vodorod", "Litiy", "Uglerod"], 1),
                    question("pH ko'rsatkichi 7 ga teng bo'lgan eritma qanday muhitga ega?", MEDIUM, "Eritmalar",
                             ["Kislotali", "Ishqoriy", "Neytral", "To'yingan"], 2),
                    question("Suvning molyar massasi nechaga teng?", MEDIUM, "Mol hisoblari",
                             ["16 g/mol", "18 g/mol", "20 g/mol", "22 g/mol"], 1),
                    question("Karbonat angidrid (CO₂) molekulasi nechta atomdan iborat?", MEDIUM, "Formulalar",
                             ["2", "3", "4", "5"], 1),
                    question("2H₂ + O₂ → 2H₂O reaksiyasida 4 mol vodorod uchun necha mol kislorod kerak?",
                             HARD, "Reaksiya tenglamalari",
                             ["1 mol", "2 mol", "4 mol", "8 mol"], 1),
                    question("Quyidagi metallardan qaysi biri xlorid kislota bilan reaksiyaga kirishmaydi?",
                             HARD, "Metallar aktivligi",
                             ["Rux (Zn)", "Temir (Fe)", "Magniy (Mg)", "Mis (Cu)"], 3),
                ],
            ),
            quiz(
                "Kimyo: mustahkamlash testi",
                "Atom tuzilishi, kislota-asos va mol hisoblari bo'yicha "
                "o'rta darajadagi 10 ta savol.",
                [
                    question("Uglerod elementining kimyoviy belgisi qaysi?", EASY, "Elementlar",
                             ["C", "Ca", "Cu", "Co"], 0),
                    question("Sulfat kislotaning formulasi qaysi?", EASY, "Formulalar",
                             ["HCl", "HNO₃", "H₂SO₄", "H₂CO₃"], 2),
                    question("Atom yadrosi qanday zarrachalardan tashkil topgan?", MEDIUM, "Atom tuzilishi",
                             ["Proton va elektron", "Proton va neytron",
                              "Neytron va elektron", "Faqat protondan"], 1),
                    question("pH ko'rsatkichi 3 ga teng bo'lgan eritma qanday muhitga ega?", MEDIUM, "Eritmalar",
                             ["Kislotali", "Neytral", "Ishqoriy", "Muhit aniqlanmaydi"], 0),
                    question("Kislorod atomining tartib raqami nechaga teng?", MEDIUM, "Davriy jadval",
                             ["6", "7", "8", "16"], 2),
                    question("Metallar kimyoviy reaksiyalarda odatda qanday zarracha bo'ladi?", MEDIUM, "Metallar",
                             ["Elektron beradi", "Elektron oladi",
                              "Elektron almashmaydi", "Proton beradi"], 0),
                    question("NaOH birikmasi qaysi sinfga mansub?", MEDIUM, "Birikmalar sinflari",
                             ["Kislota", "Asos", "Tuz", "Oksid"], 1),
                    question("CO₂ birikmasi qaysi sinfga mansub?", MEDIUM, "Birikmalar sinflari",
                             ["Kislota", "Asos", "Tuz", "Oksid"], 3),
                    question("1 mol moddada taxminan nechta zarracha bo'ladi?", HARD, "Mol hisoblari",
                             ["6,02 × 10²³", "3,14 × 10²³", "9,8 × 10²³", "1,6 × 10¹⁹"], 0),
                    question("Kislota va asos o'zaro ta'sirlashganda qanday reaksiya sodir bo'ladi?",
                             HARD, "Reaksiya turlari",
                             ["Almashinish", "Neytrallanish", "Birikish", "Parchalanish"], 1),
                ],
            ),
            quiz(
                "Kimyo: murakkab savollar testi",
                "Reaksiya tenglamalari, oksidlanish darajasi va eritmalar bo'yicha "
                "yuqori darajadagi 10 ta savol.",
                [
                    question("Metan (CH₄) molekulasida nechta vodorod atomi bor?", MEDIUM, "Organik kimyo",
                             ["2", "3", "4", "6"], 2),
                    question("Ammiakning kimyoviy formulasi qaysi?", MEDIUM, "Formulalar",
                             ["NH₃", "NO₂", "N₂O", "HNO₃"], 0),
                    question("Glyukozaning kimyoviy formulasi qaysi?", MEDIUM, "Organik kimyo",
                             ["C₆H₁₂O₆", "C₂H₅OH", "CH₃COOH", "C₁₂H₂₂O₁₁"], 0),
                    question("Etil spirtining formulasi qaysi?", MEDIUM, "Organik kimyo",
                             ["CH₃OH", "C₂H₅OH", "CH₃COOH", "C₃H₈"], 1),
                    question("H₂SO₄ tarkibidagi oltingugurtning oksidlanish darajasi nechaga teng?",
                             HARD, "Oksidlanish darajasi",
                             ["+2", "+4", "+6", "−2"], 2),
                    question("Suvdagi vodorodning oksidlanish darajasi nechaga teng?", HARD, "Oksidlanish darajasi",
                             ["−1", "0", "+1", "+2"], 2),
                    question("32 g kislorod necha molni tashkil etadi? (M(O₂) = 32 g/mol)", HARD, "Mol hisoblari",
                             ["0,5 mol", "1 mol", "2 mol", "32 mol"], 1),
                    question("CaCO₃ → CaO + CO₂ reaksiyasi qaysi turga mansub?", HARD, "Reaksiya turlari",
                             ["Birikish", "Parchalanish", "O'rin olish", "Almashinish"], 1),
                    question("Normal sharoitda 1 mol gaz qanday hajmni egallaydi?", HARD, "Gaz qonunlari",
                             ["11,2 l", "22,4 l", "24,0 l", "44,8 l"], 1),
                    question("Quyidagi metallardan qaysi biri eng faol hisoblanadi?", HARD, "Metallar aktivligi",
                             ["Mis (Cu)", "Temir (Fe)", "Rux (Zn)", "Kaliy (K)"], 3),
                ],
            ),
        ],
    },
    {
        "name": "Biologiya",
        "type": "biology",
        "icon": "leaf",
        "quizzes": [
            quiz(
                "Biologiya: asosiy bilimlar testi",
                "Hujayra, organizm va irsiyat asoslari bo'yicha "
                "10 ta savoldan iborat boshlang'ich daraja testi.",
                [
                    question("O'simliklar fotosintez jarayonida qaysi gazni yutadi?", EASY, "Fotosintez",
                             ["Kislorod", "Karbonat angidrid", "Azot", "Vodorod"], 1),
                    question("Inson organizmida qonni haydab turadigan organ qaysi?", EASY, "Odam anatomiyasi",
                             ["Jigar", "O'pka", "Yurak", "Buyrak"], 2),
                    question("Hujayraning irsiy axborotini saqlaydigan organoid qaysi?", EASY, "Hujayra",
                             ["Ribosoma", "Yadro", "Vakuola", "Lizosoma"], 1),
                    question("Voyaga yetgan inson skeleti taxminan nechta suyakdan iborat?", EASY, "Odam anatomiyasi",
                             ["106", "206", "306", "406"], 1),
                    question("Inson qonining nechta guruhi mavjud?", EASY, "Qon",
                             ["2", "3", "4", "6"], 2),
                    question("Fotosintez jarayoni hujayraning qaysi organoidida boradi?", MEDIUM, "Fotosintez",
                             ["Mitoxondriya", "Xloroplast", "Ribosoma", "Golji apparati"], 1),
                    question("Hujayraning \"energiya stansiyasi\" deb ataladigan organoidi qaysi?", MEDIUM, "Hujayra",
                             ["Yadro", "Mitoxondriya", "Vakuola", "Xloroplast"], 1),
                    question("DNK molekulasida adeninga qaysi nukleotid komplementar?", MEDIUM, "Genetika",
                             ["Guanin", "Sitozin", "Timin", "Uratsil"], 2),
                    question("Aa × Aa chatishtirishda avlodda fenotip bo'yicha qanday nisbat kuzatiladi?",
                             HARD, "Genetika",
                             ["1 : 1", "3 : 1", "9 : 3 : 3 : 1", "1 : 2 : 1"], 1),
                    question("Oqsil sintezining translatsiya bosqichi hujayraning qayerida boradi?",
                             HARD, "Molekulyar biologiya",
                             ["Yadroda", "Ribosomada", "Lizosomada", "Golji apparatida"], 1),
                ],
            ),
            quiz(
                "Biologiya: mustahkamlash testi",
                "Organ sistemalari, o'simliklar va mikroorganizmlar bo'yicha "
                "o'rta darajadagi 10 ta savol.",
                [
                    question("Inson organizmida kislorod almashinuvi qaysi organda sodir bo'ladi?",
                             EASY, "Nafas olish",
                             ["Jigar", "O'pka", "Buyrak", "Oshqozon"], 1),
                    question("O'simlikning suv va mineral moddalarni shimadigan qismi qaysi?", EASY, "O'simliklar",
                             ["Barg", "Poya", "Ildiz", "Gul"], 2),
                    question("Qonda kislorod tashiydigan hujayralar qanday ataladi?", MEDIUM, "Qon",
                             ["Leykotsitlar", "Eritrotsitlar", "Trombotsitlar", "Limfotsitlar"], 1),
                    question("Ovqat hazm qilish jarayoni asosan qaysi organda yakunlanadi?", MEDIUM, "Hazm qilish",
                             ["Oshqozonda", "Ingichka ichakda", "Yo'g'on ichakda", "Qizilo'ngachda"], 1),
                    question("Bakteriyalar hujayrasida qaysi organoid bo'lmaydi?", MEDIUM, "Mikrobiologiya",
                             ["Ribosoma", "Hujayra devori", "Shakllangan yadro", "Sitoplazma"], 2),
                    question("Fotosintez natijasida qaysi gaz ajralib chiqadi?", MEDIUM, "Fotosintez",
                             ["Azot", "Kislorod", "Karbonat angidrid", "Vodorod"], 1),
                    question("Inson tanasidagi eng yirik ichki a'zo qaysi?", MEDIUM, "Odam anatomiyasi",
                             ["Yurak", "Jigar", "Buyrak", "Taloq"], 1),
                    question("Nerv hujayrasi qanday ataladi?", MEDIUM, "Nerv sistemasi",
                             ["Neyron", "Nefron", "Akson", "Sinaps"], 0),
                    question("Mitoz bo'linish natijasida nechta hujayra hosil bo'ladi?", HARD, "Hujayra bo'linishi",
                             ["1", "2", "4", "8"], 1),
                    question("Insonning somatik hujayrasida nechta xromosoma bo'ladi?", HARD, "Genetika",
                             ["23", "44", "46", "48"], 2),
                ],
            ),
            quiz(
                "Biologiya: murakkab savollar testi",
                "Genetika, moddalar almashinuvi va evolyutsiya bo'yicha "
                "yuqori darajadagi 10 ta savol.",
                [
                    question("DNK molekulasida guaninga qaysi nukleotid komplementar?", MEDIUM, "Genetika",
                             ["Adenin", "Timin", "Sitozin", "Uratsil"], 2),
                    question("RNK molekulasida timin o'rniga qaysi nukleotid keladi?", MEDIUM, "Molekulyar biologiya",
                             ["Adenin", "Guanin", "Sitozin", "Uratsil"], 3),
                    question("Oqsil sintezining transkripsiya bosqichi qayerda boradi?", MEDIUM, "Molekulyar biologiya",
                             ["Yadroda", "Ribosomada", "Mitoxondriyada", "Lizosomada"], 0),
                    question("Insonning jinsiy hujayrasida nechta xromosoma bo'ladi?", MEDIUM, "Genetika",
                             ["21", "23", "46", "92"], 1),
                    question("Meyoz bo'linish natijasida nechta hujayra hosil bo'ladi?", HARD, "Hujayra bo'linishi",
                             ["1", "2", "4", "8"], 2),
                    question("Aa × aa chatishtirishda avlodda qanday nisbat kuzatiladi?", HARD, "Genetika",
                             ["1 : 1", "3 : 1", "1 : 2 : 1", "9 : 3 : 3 : 1"], 0),
                    question("Tabiiy tanlanish nazariyasini kim ishlab chiqqan?", HARD, "Evolyutsiya",
                             ["Gregor Mendel", "Charlz Darvin", "Lui Paster", "Karl Linney"], 1),
                    question("Irsiyat qonunlarini birinchi bo'lib kim kashf etgan?", HARD, "Genetika",
                             ["Charlz Darvin", "Gregor Mendel", "Tomas Morgan", "Jeyms Uotson"], 1),
                    question("Hujayrada nafas olish jarayoni asosan qaysi organoidda boradi?",
                             HARD, "Moddalar almashinuvi",
                             ["Xloroplastda", "Mitoxondriyada", "Ribosomada", "Yadroda"], 1),
                    question("Genetik kodda bitta aminokislotani nechta nukleotid belgilaydi?",
                             HARD, "Molekulyar biologiya",
                             ["1", "2", "3", "4"], 2),
                ],
            ),
        ],
    },
    {
        "name": "Tarix",
        "type": "history",
        "icon": "graduate",
        "quizzes": [
            quiz(
                "Tarix: asosiy bilimlar testi",
                "Vatan tarixi va jahon tarixining muhim sanalari bo'yicha "
                "10 ta savoldan iborat boshlang'ich daraja testi.",
                [
                    question("Amir Temur davlatining poytaxti qaysi shahar bo'lgan?", EASY, "Temuriylar davri",
                             ["Buxoro", "Samarqand", "Xiva", "Toshkent"], 1),
                    question("O'zbekiston mustaqilligi qaysi yilda e'lon qilingan?", EASY, "Mustaqillik",
                             ["1989", "1990", "1991", "1992"], 2),
                    question("Ikkinchi jahon urushi qaysi yilda tugagan?", EASY, "Jahon tarixi",
                             ["1939", "1943", "1945", "1947"], 2),
                    question("Registon majmuasi qaysi shaharda joylashgan?", EASY, "Me'moriy yodgorliklar",
                             ["Buxoro", "Samarqand", "Shahrisabz", "Xiva"], 1),
                    question("Buyuk ipak yo'li asosan qaysi mintaqalarni bog'lagan?", EASY, "Savdo yo'llari",
                             ["Xitoy va Yevropani", "Afrika va Amerikani",
                              "Hindiston va Avstraliyani", "Rossiya va Yaponiyani"], 0),
                    question("Amir Temur qaysi yilda tug'ilgan?", MEDIUM, "Temuriylar davri",
                             ["1316", "1326", "1336", "1346"], 2),
                    question("Mirzo Ulug'bek birinchi navbatda qaysi soha olimi sifatida mashhur?", MEDIUM, "Ilm-fan tarixi",
                             ["Tibbiyot", "Astronomiya", "Geografiya", "Kimyo"], 1),
                    question("Zahiriddin Muhammad Bobur qaysi davlatga asos solgan?", MEDIUM, "Boburiylar",
                             ["Safaviylar davlati", "Usmonlilar imperiyasi",
                              "Boburiylar saltanati", "Somoniylar davlati"], 2),
                    question("1402-yilgi Anqara jangida Amir Temur kimni mag'lub etgan?", HARD, "Temuriylar davri",
                             ["Sulton Boyazid I ni", "To'xtamishxonni", "Shohruhni", "Sulton Mahmudni"], 0),
                    question("Somoniylar davlatining poytaxti qaysi shahar bo'lgan?", HARD, "O'rta asrlar",
                             ["Samarqand", "Buxoro", "Urganch", "Marv"], 1),
                ],
            ),
            quiz(
                "Tarix: mustahkamlash testi",
                "O'rta asrlar Markaziy Osiyosi, xonliklar davri va XX asr "
                "voqealari bo'yicha o'rta darajadagi 10 ta savol.",
                [
                    question("O'zbekiston Respublikasi Konstitutsiyasi qaysi yilda qabul qilingan?",
                             EASY, "Mustaqillik",
                             ["1991", "1992", "1993", "1995"], 1),
                    question("Birinchi jahon urushi qaysi yilda boshlangan?", EASY, "Jahon tarixi",
                             ["1905", "1914", "1918", "1939"], 1),
                    question("Ichan qal'a me'moriy majmuasi qaysi shaharda joylashgan?", MEDIUM, "Me'moriy yodgorliklar",
                             ["Buxoro", "Samarqand", "Xiva", "Qo'qon"], 2),
                    question("Mirzo Ulug'bek rasadxonasi qaysi shaharda qurilgan?", MEDIUM, "Ilm-fan tarixi",
                             ["Buxoro", "Samarqand", "Toshkent", "Termiz"], 1),
                    question("\"Al-Jabr\" asari muallifi — algebra faniga asos solgan olim kim?",
                             MEDIUM, "Ilm-fan tarixi",
                             ["Abu Rayhon Beruniy", "Al-Xorazmiy", "Ibn Sino", "Al-Farg'oniy"], 1),
                    question("\"Tib qonunlari\" asarining muallifi kim?", MEDIUM, "Ilm-fan tarixi",
                             ["Al-Xorazmiy", "Ibn Sino", "Beruniy", "Al-Buxoriy"], 1),
                    question("XVI–XIX asrlarda Markaziy Osiyoda nechta xonlik mavjud bo'lgan?",
                             MEDIUM, "Xonliklar davri",
                             ["Ikkita", "Uchta", "To'rtta", "Beshta"], 1),
                    question("Buyuk Britaniya mustamlakasidan Hindiston qaysi yilda mustaqil bo'lgan?",
                             MEDIUM, "Jahon tarixi",
                             ["1945", "1947", "1950", "1960"], 1),
                    question("Amir Temur vafotidan keyin taxtga kim o'tirgan?", HARD, "Temuriylar davri",
                             ["Shohruh Mirzo", "Mirzo Ulug'bek", "Xalil Sulton", "Bobur"], 2),
                    question("Buxoro amirligi qaysi yilda tugatilgan?", HARD, "XX asr tarixi",
                             ["1917", "1920", "1924", "1929"], 1),
                ],
            ),
            quiz(
                "Tarix: murakkab savollar testi",
                "Qadimgi davlatlar, Temuriylar sulolasi va jahon tarixining "
                "burilish nuqtalari bo'yicha yuqori darajadagi 10 ta savol.",
                [
                    question("Buyuk Iskandar Markaziy Osiyoga qaysi asrda yurish qilgan?", MEDIUM, "Qadimgi davrlar",
                             ["Mil. avv. VI asr", "Mil. avv. IV asr", "Mil. avv. II asr", "Mil. I asr"], 1),
                    question("Amir Temur qaysi shaharda tug'ilgan?", MEDIUM, "Temuriylar davri",
                             ["Samarqandda", "Shahrisabzda", "Buxoroda", "Termizda"], 1),
                    question("Mirzo Ulug'bekning mashhur astronomik asari qanday nomlanadi?",
                             MEDIUM, "Ilm-fan tarixi",
                             ["Zij", "Qonun", "Xamsa", "Shajara"], 0),
                    question("Bobur o'zining mashhur memuar asarini qanday nomlagan?", MEDIUM, "Boburiylar",
                             ["Boburnoma", "Temurnoma", "Shohnoma", "Zafarnoma"], 0),
                    question("Amudaryo qadimda qanday nom bilan atalgan?", HARD, "Qadimgi davrlar",
                             ["Yaksart", "Oks (Amul)", "Zarafshon", "Tanais"], 1),
                    question("Sirdaryo qadimgi manbalarda qanday atalgan?", HARD, "Qadimgi davrlar",
                             ["Oks", "Yaksart", "Murg'ob", "Balxob"], 1),
                    question("Amir Temur vafot etgan yil qaysi?", HARD, "Temuriylar davri",
                             ["1395", "1402", "1405", "1410"], 2),
                    question("Konstantinopol usmonlilar tomonidan qaysi yilda zabt etilgan?",
                             HARD, "Jahon tarixi",
                             ["1389", "1453", "1492", "1517"], 1),
                    question("Buyuk geografik kashfiyotlar davri qaysi asrda boshlangan?", HARD, "Jahon tarixi",
                             ["XIII asr", "XV asr", "XVII asr", "XIX asr"], 1),
                    question("Somoniylar davlati qaysi asrlarda hukmronlik qilgan?", HARD, "O'rta asrlar",
                             ["VI–VII asrlar", "IX–X asrlar", "XII–XIII asrlar", "XIV–XV asrlar"], 1),
                ],
            ),
        ],
    },
    {
        "name": "Geografiya",
        "type": "geography",
        "icon": "leaf",
        "quizzes": [
            quiz(
                "Geografiya: asosiy bilimlar testi",
                "Tabiiy geografiya va O'zbekiston geografiyasi bo'yicha "
                "10 ta savoldan iborat boshlang'ich daraja testi.",
                [
                    question("O'zbekiston Respublikasining poytaxti qaysi shahar?", EASY, "O'zbekiston geografiyasi",
                             ["Samarqand", "Toshkent", "Buxoro", "Namangan"], 1),
                    question("Yer yuzidagi eng katta okean qaysi?", EASY, "Okeanlar",
                             ["Atlantika okeani", "Hind okeani", "Tinch okeani", "Shimoliy Muz okeani"], 2),
                    question("Yer yuzidagi eng baland tog' cho'qqisi qaysi?", EASY, "Tog'lar",
                             ["Everest (Jomolungma)", "Elbrus", "Kilimanjaro", "Mont-Blan"], 0),
                    question("O'zbekistonda nechta viloyat mavjud?", EASY, "O'zbekiston geografiyasi",
                             ["10", "12", "14", "16"], 1),
                    question("Sahroi Kabir qaysi qit'ada joylashgan?", EASY, "Qit'alar",
                             ["Osiyo", "Afrika", "Avstraliya", "Janubiy Amerika"], 1),
                    question("O'zbekistondagi eng uzun daryo qaysi?", MEDIUM, "Daryolar",
                             ["Sirdaryo", "Amudaryo", "Zarafshon", "Chirchiq"], 1),
                    question("Yer o'z o'qi atrofida bir marta necha soatda aylanadi?", MEDIUM, "Yer harakati",
                             ["12 soat", "24 soat", "365 soat", "48 soat"], 1),
                    question("O'zbekiston nechta davlat bilan chegaradosh?", MEDIUM, "O'zbekiston geografiyasi",
                             ["3", "4", "5", "6"], 2),
                    question("Yer yuzidagi eng chuqur ko'l qaysi?", HARD, "Ko'llar",
                             ["Kaspiy dengizi", "Baykal", "Tanganika", "Viktoriya"], 1),
                    question("O'zbekistonning eng baland cho'qqisi qaysi?", HARD, "Tog'lar",
                             ["Chimyon", "Xazrat Sulton", "Beshtor", "Oqtosh"], 1),
                ],
            ),
            quiz(
                "Geografiya: mustahkamlash testi",
                "Qit'alar, iqlim va O'zbekiston tabiati bo'yicha o'rta darajadagi "
                "10 ta savol.",
                [
                    question("Yer yuzida nechta qit'a mavjud?", EASY, "Qit'alar",
                             ["5", "6", "7", "8"], 2),
                    question("Eng kichik qit'a qaysi?", EASY, "Qit'alar",
                             ["Yevropa", "Avstraliya", "Antarktida", "Janubiy Amerika"], 1),
                    question("Yer yuzidagi eng uzun daryo qaysi hisoblanadi?", MEDIUM, "Daryolar",
                             ["Amazonka", "Nil", "Yanszi", "Missisipi"], 1),
                    question("O'zbekiston qaysi iqlim mintaqasida joylashgan?", MEDIUM, "Iqlim",
                             ["Tropik", "Subtropik va mo'tadil", "Arktika", "Ekvatorial"], 1),
                    question("Orol dengizi asosan qaysi ikki daryodan suv olgan?", MEDIUM, "Ekologiya",
                             ["Chirchiq va Ohangaron", "Amudaryo va Sirdaryo",
                              "Zarafshon va Qashqadaryo", "Surxondaryo va Zarafshon"], 1),
                    question("Yer o'zining Quyosh atrofidagi to'liq aylanishini qancha vaqtda bajaradi?",
                             MEDIUM, "Yer harakati",
                             ["24 soat", "30 kun", "365 kun", "12 yil"], 2),
                    question("Ekvator Yerni nechta yarim sharga bo'ladi?", MEDIUM, "Kartografiya",
                             ["2", "3", "4", "6"], 0),
                    question("Qizilqum cho'li asosan qaysi davlatlar hududida joylashgan?",
                             MEDIUM, "O'zbekiston geografiyasi",
                             ["Qozog'iston va Qirg'iziston", "O'zbekiston va Qozog'iston",
                              "Tojikiston va Afg'oniston", "Turkmaniston va Eron"], 1),
                    question("Yer yuzidagi eng katta qit'a qaysi?", HARD, "Qit'alar",
                             ["Afrika", "Osiyo", "Shimoliy Amerika", "Antarktida"], 1),
                    question("Tog'ga ko'tarilganda havo harorati odatda qanday o'zgaradi?", HARD, "Iqlim",
                             ["Ortadi", "Pasayadi", "O'zgarmaydi", "Avval ortadi, keyin pasayadi"], 1),
                ],
            ),
            quiz(
                "Geografiya: murakkab savollar testi",
                "Koordinatalar, tabiat zonalari va dunyo geografiyasi bo'yicha "
                "yuqori darajadagi 10 ta savol.",
                [
                    question("Grinvich meridiani necha gradusga teng?", MEDIUM, "Kartografiya",
                             ["0°", "45°", "90°", "180°"], 0),
                    question("Yer yuzidagi eng katta orol qaysi?", MEDIUM, "Orollar",
                             ["Madagaskar", "Grenlandiya", "Yangi Gvineya", "Kalimantan"], 1),
                    question("Toshkent taxminan qaysi kenglikda joylashgan?", MEDIUM, "Koordinatalar",
                             ["21° sh.k.", "31° sh.k.", "41° sh.k.", "51° sh.k."], 2),
                    question("Baykal ko'li qaysi davlat hududida joylashgan?", MEDIUM, "Ko'llar",
                             ["Xitoy", "Mo'g'uliston", "Rossiya", "Qozog'iston"], 2),
                    question("Yer yuzidagi eng katta cho'l qaysi?", HARD, "Cho'llar",
                             ["Qoraqum", "Gobi", "Sahroi Kabir", "Kalahari"], 2),
                    question("Amazonka daryosi qaysi okeanga quyiladi?", HARD, "Daryolar",
                             ["Tinch okeaniga", "Atlantika okeaniga",
                              "Hind okeaniga", "Shimoliy Muz okeaniga"], 1),
                    question("Yer yuzasining taxminan necha foizini suv egallaydi?", HARD, "Gidrosfera",
                             ["51%", "61%", "71%", "81%"], 2),
                    question("Vulqonlar va zilzilalar eng ko'p uchraydigan mintaqa qanday ataladi?",
                             HARD, "Litosfera",
                             ["Tinch okeani olov halqasi", "Buyuk cho'l mintaqasi",
                              "Ekvatorial mintaqa", "Shimoliy qutb mintaqasi"], 0),
                    question("O'zbekistonda eng ko'p yog'in qaysi hududlarga tushadi?", HARD, "Iqlim",
                             ["Cho'l hududlariga", "Tog' oldi va tog' hududlariga",
                              "Orol bo'yiga", "Vodiy markaziga"], 1),
                    question("Kaspiy dengizi aslida nima hisoblanadi?", HARD, "Ko'llar",
                             ["Okean qismi", "Dunyodagi eng katta ko'l",
                              "Sun'iy suv ombori", "Ichki dengiz qo'ltig'i"], 1),
                ],
            ),
        ],
    },
    {
        "name": "Ona tili va adabiyoti",
        "type": "native_language",
        "icon": "graduate",
        "quizzes": [
            quiz(
                "Ona tili va adabiyoti: asosiy bilimlar testi",
                "O'zbek tili qoidalari va o'zbek adabiyoti bo'yicha "
                "10 ta savoldan iborat boshlang'ich daraja testi.",
                [
                    question("Hozirgi o'zbek lotin alifbosida nechta harf bor?", EASY, "Alifbo",
                             ["26", "29", "33", "36"], 1),
                    question("\"Alpomish\" asari qaysi janrga mansub?", EASY, "Xalq og'zaki ijodi",
                             ["She'r", "Doston", "Roman", "Hikoya"], 1),
                    question("Alisher Navoiyning \"Xamsa\" asari nechta dostondan iborat?", EASY, "Navoiy ijodi",
                             ["3", "4", "5", "6"], 2),
                    question("Gapning bosh bo'laklari qaysilar?", EASY, "Sintaksis",
                             ["Ega va kesim", "Aniqlovchi va to'ldiruvchi",
                              "Hol va aniqlovchi", "Kesim va hol"], 0),
                    question("\"Kitob\" so'zi qaysi so'z turkumiga mansub?", EASY, "Morfologiya",
                             ["Ot", "Sifat", "Fe'l", "Ravish"], 0),
                    question("\"O'tkan kunlar\" romanining muallifi kim?", MEDIUM, "XX asr adabiyoti",
                             ["Cho'lpon", "Abdulla Qodiriy", "Oybek", "Abdulla Qahhor"], 1),
                    question("So'zning ma'no anglatuvchi o'zgarmas qismi qanday ataladi?", MEDIUM, "Morfologiya",
                             ["Qo'shimcha", "O'zak", "Bo'g'in", "Urg'u"], 1),
                    question("\"Sarob\" romanining muallifi kim?", MEDIUM, "XX asr adabiyoti",
                             ["Abdulla Qodiriy", "Abdulla Qahhor", "Oybek", "Cho'lpon"], 1),
                    question("Alisher Navoiy \"Xamsa\"sining birinchi dostoni qaysi?", HARD, "Navoiy ijodi",
                             ["Farhod va Shirin", "Hayrat ul-abror",
                              "Layli va Majnun", "Saddi Iskandariy"], 1),
                    question("\"Navoiy\" tarixiy romanining muallifi kim?", HARD, "XX asr adabiyoti",
                             ["Oybek", "G'afur G'ulom", "Said Ahmad", "Pirimqul Qodirov"], 0),
                ],
            ),
            quiz(
                "Ona tili va adabiyoti: mustahkamlash testi",
                "So'z turkumlari, gap bo'laklari va XX asr o'zbek adabiyoti "
                "bo'yicha o'rta darajadagi 10 ta savol.",
                [
                    question("\"Chiroyli\" so'zi qaysi so'z turkumiga mansub?", EASY, "Morfologiya",
                             ["Ot", "Sifat", "Fe'l", "Son"], 1),
                    question("\"Yozmoq\" so'zi qaysi so'z turkumiga mansub?", EASY, "Morfologiya",
                             ["Ot", "Sifat", "Fe'l", "Ravish"], 2),
                    question("Gapda ish-harakatni bildiruvchi bosh bo'lak qanday ataladi?", MEDIUM, "Sintaksis",
                             ["Ega", "Kesim", "To'ldiruvchi", "Hol"], 1),
                    question("Gapning ikkinchi darajali bo'laklari qaysilar?", MEDIUM, "Sintaksis",
                             ["Ega, kesim, hol", "To'ldiruvchi, aniqlovchi, hol",
                              "Ega, aniqlovchi", "Kesim, to'ldiruvchi"], 1),
                    question("\"Mehrobdan chayon\" asarining muallifi kim?", MEDIUM, "XX asr adabiyoti",
                             ["Abdulla Qodiriy", "Oybek", "Cho'lpon", "Abdulla Qahhor"], 0),
                    question("\"Kecha va kunduz\" romanining muallifi kim?", MEDIUM, "XX asr adabiyoti",
                             ["Abdulla Qodiriy", "Cho'lpon", "Oybek", "G'afur G'ulom"], 1),
                    question("So'zga qo'shilib, yangi so'z yasaydigan qo'shimcha qanday ataladi?",
                             MEDIUM, "So'z yasalishi",
                             ["Shakl yasovchi", "So'z yasovchi", "Egalik qo'shimchasi", "Kelishik qo'shimchasi"], 1),
                    question("O'zbek tilida nechta kelishik mavjud?", MEDIUM, "Morfologiya",
                             ["4", "5", "6", "7"], 2),
                    question("\"O'tkan kunlar\" romani qaysi yillarda yozilgan?", HARD, "XX asr adabiyoti",
                             ["1900-yillar", "1920-yillar", "1940-yillar", "1960-yillar"], 1),
                    question("Alisher Navoiy qaysi shaharda tug'ilgan?", HARD, "Navoiy ijodi",
                             ["Samarqandda", "Hirotda", "Buxoroda", "Toshkentda"], 1),
                ],
            ),
            quiz(
                "Ona tili va adabiyoti: murakkab savollar testi",
                "Mumtoz adabiyot, adabiy janrlar va til nazariyasi bo'yicha "
                "yuqori darajadagi 10 ta savol.",
                [
                    question("\"Boburnoma\" asari qaysi janrga mansub?", MEDIUM, "Mumtoz adabiyot",
                             ["Doston", "Memuar (esdalik)", "Roman", "Qissa"], 1),
                    question("Alisher Navoiy \"Xamsa\"sining oxirgi dostoni qaysi?", MEDIUM, "Navoiy ijodi",
                             ["Hayrat ul-abror", "Farhod va Shirin",
                              "Sab'ai sayyor", "Saddi Iskandariy"], 3),
                    question("To'rt misradan iborat she'riy shakl qanday ataladi?", MEDIUM, "Adabiyot nazariyasi",
                             ["G'azal", "Ruboiy", "Qasida", "Masnaviy"], 1),
                    question("\"Ikki eshik orasi\" romanining muallifi kim?", MEDIUM, "XX asr adabiyoti",
                             ["O'tkir Hoshimov", "Said Ahmad", "Shukur Xolmirzayev", "Odil Yoqubov"], 0),
                    question("O'zbek mumtoz adabiyotida g'azal odatda nechta baytdan iborat bo'ladi?",
                             HARD, "Adabiyot nazariyasi",
                             ["2–4 bayt", "5–9 bayt", "10–15 bayt", "20 dan ortiq bayt"], 1),
                    question("\"Ulug'bek xazinasi\" romanining muallifi kim?", HARD, "XX asr adabiyoti",
                             ["Oybek", "Odil Yoqubov", "Pirimqul Qodirov", "Mirmuhsin"], 1),
                    question("\"Yulduzli tunlar\" romani kim haqida yozilgan?", HARD, "XX asr adabiyoti",
                             ["Amir Temur", "Bobur", "Mirzo Ulug'bek", "Alisher Navoiy"], 1),
                    question("Alisher Navoiy asarlarini asosan qaysi tilda yozgan?", HARD, "Navoiy ijodi",
                             ["Fors tilida", "Eski o'zbek (turkiy) tilida",
                              "Arab tilida", "Chig'atoy-mo'g'ul tilida"], 1),
                    question("Bir xil undosh bilan boshlanuvchi so'zlarning takrorlanishi qanday ataladi?",
                             HARD, "Adabiyot nazariyasi",
                             ["Alliteratsiya", "Metafora", "Epitet", "Giperbola"], 0),
                    question("O'xshatish asosida ko'chma ma'no hosil qilish qanday ataladi?",
                             HARD, "Adabiyot nazariyasi",
                             ["Metafora", "Sinonim", "Antonim", "Omonim"], 0),
                ],
            ),
        ],
    },
    {
        "name": "Ingliz tili",
        "type": "english",
        "icon": "graduate",
        "quizzes": [
            quiz(
                "Ingliz tili: asosiy bilimlar testi",
                "Lug'at boyligi va grammatika asoslari bo'yicha "
                "10 ta savoldan iborat boshlang'ich daraja testi.",
                [
                    question("\"Book\" so'zi o'zbek tilida nimani anglatadi?", EASY, "Lug'at",
                             ["Daftar", "Kitob", "Ruchka", "Stol"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"I ___ a student.\"", EASY, "To be fe'li",
                             ["is", "are", "am", "be"], 2),
                    question("\"Apple\" so'zi o'zbek tilida nimani anglatadi?", EASY, "Lug'at",
                             ["Olma", "Nok", "Uzum", "Anor"], 0),
                    question("\"Child\" so'zining ko'plik shakli qaysi?", EASY, "Ot ko'pligi",
                             ["childs", "childes", "children", "childrens"], 2),
                    question("\"Good morning\" iborasi qanday tarjima qilinadi?", EASY, "Muomala iboralari",
                             ["Xayrli kech", "Xayrli tong", "Xayrli tun", "Xayr"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"She ___ to school every day.\"", MEDIUM, "Present Simple",
                             ["go", "goes", "going", "gone"], 1),
                    question("\"Go\" fe'lining Past Simple shakli qaysi?", MEDIUM, "Past Simple",
                             ["goed", "gone", "went", "going"], 2),
                    question("Bo'sh o'rinni to'ldiring: \"There ___ three books on the table.\"", MEDIUM, "There is / there are",
                             ["is", "are", "was", "be"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"If I ___ rich, I would travel the world.\"",
                             HARD, "Conditionals",
                             ["am", "was", "were", "will be"], 2),
                    question("Bo'sh o'rinni to'ldiring: \"He said he ___ finished the work.\"",
                             HARD, "Reported speech",
                             ["has", "had", "have", "having"], 1),
                ],
            ),
            quiz(
                "Ingliz tili: mustahkamlash testi",
                "Zamonlar, sifat darajalari va predloglar bo'yicha o'rta "
                "darajadagi 10 ta savol.",
                [
                    question("\"Water\" so'zi o'zbek tilida nimani anglatadi?", EASY, "Lug'at",
                             ["Non", "Suv", "Sut", "Choy"], 1),
                    question("\"Man\" so'zining ko'plik shakli qaysi?", EASY, "Ot ko'pligi",
                             ["mans", "mens", "men", "manes"], 2),
                    question("Bo'sh o'rinni to'ldiring: \"They ___ watching TV now.\"", MEDIUM, "Present Continuous",
                             ["is", "am", "are", "be"], 2),
                    question("\"Big\" sifatining orttirma darajasi qaysi?", MEDIUM, "Sifat darajalari",
                             ["biger", "bigger", "biggest", "more big"], 2),
                    question("\"Good\" sifatining qiyosiy darajasi qaysi?", MEDIUM, "Sifat darajalari",
                             ["gooder", "better", "best", "more good"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"I have lived here ___ 2015.\"", MEDIUM, "Predloglar",
                             ["for", "since", "from", "during"], 1),
                    question("\"Buy\" fe'lining Past Simple shakli qaysi?", MEDIUM, "Past Simple",
                             ["buyed", "bought", "brought", "buying"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"She has ___ her homework.\"", MEDIUM, "Present Perfect",
                             ["do", "did", "done", "doing"], 2),
                    question("Bo'sh o'rinni to'ldiring: \"This book is ___ than that one.\"",
                             HARD, "Sifat darajalari",
                             ["interesting", "more interesting", "most interesting", "interestinger"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"The letter ___ yesterday.\"", HARD, "Passive Voice",
                             ["sent", "was sent", "is sent", "has sent"], 1),
                ],
            ),
            quiz(
                "Ingliz tili: murakkab savollar testi",
                "Passive Voice, Conditionals, Reported Speech va modal fe'llar "
                "bo'yicha yuqori darajadagi 10 ta savol.",
                [
                    question("Bo'sh o'rinni to'ldiring: \"You ___ wear a helmet. It is a rule.\"",
                             MEDIUM, "Modal fe'llar",
                             ["can", "must", "may", "might"], 1),
                    question("\"Write\" fe'lining Past Participle shakli qaysi?", MEDIUM, "Noto'g'ri fe'llar",
                             ["writed", "wrote", "written", "writing"], 2),
                    question("Bo'sh o'rinni to'ldiring: \"If it rains, we ___ at home.\"",
                             MEDIUM, "First Conditional",
                             ["stay", "will stay", "stayed", "would stay"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"English ___ all over the world.\"",
                             MEDIUM, "Passive Voice",
                             ["speaks", "is spoken", "spoke", "speaking"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"She asked me where I ___ from.\"",
                             HARD, "Reported speech",
                             ["come", "came", "will come", "coming"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"If I had studied, I ___ the exam.\"",
                             HARD, "Third Conditional",
                             ["would pass", "will pass", "would have passed", "had passed"], 2),
                    question("Bo'sh o'rinni to'ldiring: \"He ___ working here for five years.\"",
                             HARD, "Present Perfect Continuous",
                             ["is", "has been", "have been", "was"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"The house ___ built in 1990.\"", HARD, "Passive Voice",
                             ["is", "was", "has", "were"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"I wish I ___ more free time.\"", HARD, "Wish clauses",
                             ["have", "had", "will have", "having"], 1),
                    question("Bo'sh o'rinni to'ldiring: \"By next year he ___ his studies.\"",
                             HARD, "Future Perfect",
                             ["finishes", "will finish", "will have finished", "finished"], 2),
                ],
            ),
        ],
    },
]
